version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: monthly
    time: "04:00"
  open-pull-requests-limit: 10
  versioning-strategy: increase-if-necessary
  ignore:
  - dependency-name: phpstan/phpstan
    versions:
    - 0.12.64
    - 0.12.70
  - dependency-name: prestashop/php-dev-tools
    versions:
    - "3.13"
  - dependency-name: symfony/lock
    versions:
    - 4.4.18
  - dependency-name: symfony/finder
    versions:
    - 4.4.18
  - dependency-name: symfony/yaml
    versions:
    - 4.4.18
  - dependency-name: symfony/filesystem
    versions:
    - 4.4.18
