name: Build && Release draft
on:
  push:
    branches:
      - deploy

jobs:
  deploy:
    name: build dependencies & create artifact
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v2.0.0
        - name: Install composer dependencies
          run: composer install --no-dev -o
        - name: build phar
          run: php build.php
        - name: Create & upload artifact
            uses: actions/upload-artifact@v1
            with:
              name: prestashopConsole.phar
              path: bin/phar/prestashopConsole.phar